services:
  n8n:
    image: custom-n8n:2.1.5
    build: .
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_RUNNERS_ENABLED=true
      - GENERIC_TIMEZONE=Asia/Kolkata
      - TZ=Asia/Kolkata
    restart: unless-stopped

volumes:
  n8n_data:
